#!/sbin/busybox sh

cd /

/sbin/busybox mkdir /tmp
/sbin/busybox mount -t tmpfs tmpfs /tmp
/sbin/busybox mount -t proc proc /proc
/sbin/busybox sed -e 's/fps\=4569/fps\=4569 androidboot\.selinux\=permissive/' /proc/cmdline > /tmp/cmdline
/sbin/busybox mount --bind -o ro /tmp/cmdline /proc/cmdline

/sbin/busybox chmod 755 /init2
/sbin/busybox mv /init2 /init
exec /init
